apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unwebsockify-helm.fullname" . }}
  labels:
    {{- include "unwebsockify-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "unwebsockify-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "unwebsockify-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "unwebsockify-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - '/usr/src/app/unwebsockify.py'
          args:
            {{- if .Values.unwebsockify.subprotocol }}
            - "--subprotocol {{ .Values.unwebsockify.subprotocol }}"
            {{- end }}
            - {{ .Values.unwebsockify.url }}
          ports:
            - name: unwebsockify
              containerPort: 13232
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: unwebsockify
          readinessProbe:
            tcpSocket:
              port: unwebsockify
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
